# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0002_auto_20180615_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldocument',
            name='nr_doc',
            field=models.CharField(default=124, max_length=20),
            preserve_default=False,
        ),
    ]
