# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-11 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrental', '0003_ldocument_nr_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_doc', models.CharField(max_length=20)),
                ('osum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityrc', models.IntegerField()),
                ('sincew', models.DateField()),
                ('untilw', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ldocument',
            name='car',
        ),
        migrations.RemoveField(
            model_name='ldocument',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LDocument',
        ),
        migrations.AddField(
            model_name='positioninorder',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrental.Car'),
        ),
        migrations.AddField(
            model_name='order',
            name='pio',
            field=models.ManyToManyField(to='carrental.PositionInOrder'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
