# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-15 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servcie',
            new_name='Service',
        ),
    ]
